# Скачивает образ приложения web из docker hub.
# Используется для запуска проета на облачном сервере.

version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  web:
    image: voitekhovich/foodgram:1.0.1
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_value:/code/static
      - media_value:/code/media
      - ./data/ingredient.json:/code/ingredient.json
      - ./data/tag.json:/code/tag.json
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/result_build
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - nginx
